# Generated by Django 4.2 on 2026-05-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTankSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='tanks.tank')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailytanksale',
            constraint=models.UniqueConstraint(fields=['tank', 'date'], name='unique_tank_date'),
        ),
    ]
