# Generated by Django 4.2 on 2026-05-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0002_dailytanksale'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tankvolume',
            index=models.Index(fields=['tank', 'created_at'], name='tanks_tankv_tank_id_cd025b_idx'),
        ),
    ]
